### ISSUE TITLE
Please add a screen shot so I can add it to awesome-zsh-plugins

### ISSUE THREAD

**Issue by unixorn** [babette-landmesser/babette.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by babette-landmesser** [comment]
Hi, 
I've added a screenshot and a more explaining readme. Check if you like it. Thank you for your issue!
